version: "3.3"

services:
  web_static:
    build: ./web-static
    ports:
      - 8080:8080
    networks:
      - web
  
  web_ui:
    build: ./web-ui
    ports:
      - 8081:8081
    networks:
      - web

  haproxy:
    image: haproxy
    depends_on:
      - web_static
      - web_ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 9000:9000
    networks:
      - web

networks:
  web:
    driver: overlay
