version: '3.7'

services:
  web_static:
    build: ./web-static
    #expose:
    #  - "8080"
    environment:
     - SERVICE_PORTS=8080
    networks:
      - web
  
  web_ui:
    build: ./web-ui
    #expose:
    #  - "8081"
    environment:
     - SERVICE_PORTS=8081
    networks:
      - web

  haproxy:
    image: haproxy
    depends_on:
      - web_static
      - web_ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
    networks:
      - web
    #deploy:
    #  placement:
    #    constraints: [node.role == manager]

networks:
  web:
    driver: overlay
